## 1. Import Dependencies

In [1]:
import tensorflow as tf

## 1.1 Introductions to tensors

In [4]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [5]:
tensor_one_d = tf.constant([2,0,-3,8,90.])
print(tensor_one_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)


In [15]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d)
print(tensor_two_d.shape)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)
(4, 3)


In [24]:
tensor_three_d = tf.constant([
    [[1,2,0],
     [3,5,-1]],
    
    [[10,2,0],
     [1,0,2]],
    
    [[5,8,0],
     [2,7,0]],
    
    [[2,1,9],
     [4,-3,32]]
])
print(tensor_three_d)
print(tensor_three_d.ndim)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)
3


In [44]:
tensor_four_d = tf.constant([
    [[[1,2,0],
     [3,5,-1]],
    
    [[10,2,0],
     [1,0,2]],
    
    [[5,8,0],
     [2,7,0]],
    
    [[2,1,9],
     [4,-3,32]]],
     [[[1,2,0],
     [3,5,-1]],
    
    [[10,2,0],
     [1,0,2]],
    
    [[5,8,0],
     [2,7,0]],
    
    [[2,1,9],
     [4,-3,32]]]
], dtype=tf.float32)
print(tensor_four_d.shape)
print(tensor_four_d.ndim)
print(tensor_four_d)

(2, 4, 2, 3)
4
tf.Tensor(
[[[[ 1  2  0]
   [ 3  5 -1]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2  1  9]
   [ 4 -3 32]]]


 [[[ 1  2  0]
   [ 3  5 -1]]

  [[10  2  0]
   [ 1  0  2]]

  [[ 5  8  0]
   [ 2  7  0]]

  [[ 2  1  9]
   [ 4 -3 32]]]], shape=(2, 4, 2, 3), dtype=int8)


## 1.2 Tensor Casting

In [58]:
import numpy as np

In [49]:
casted_tensor_one_d = tf.cast(tensor_one_d, dtype=tf.bool)
print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)
tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)


In [51]:
tensor_bool = tf.constant([True, True, False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [57]:
casted_string = tf.constant(["hello world", "hi"])

In [59]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [61]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int32)


In [65]:
eye_tensor = tf.eye(num_rows=3)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)
