## 1. Import Dependencies

In [1]:
import tensorflow as tf

## 1.1 Introductions to tensors

In [2]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
tensor_one_d = tf.constant([2,0,-3,8,90.])
print(tensor_one_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)


In [4]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d)
print(tensor_two_d.shape)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)
(4, 3)


In [5]:
tensor_three_d = tf.constant([
    [[1,2,0],
     [3,5,-1]],
    
    [[10,2,0],
     [1,0,2]],
    
    [[5,8,0],
     [2,7,0]],
    
    [[2,1,9],
     [4,-3,32]]
])
print(tensor_three_d)
print(tensor_three_d.ndim)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)
3


In [6]:
tensor_four_d = tf.constant([
    [[[1,2,0],
     [3,5,-1]],
    
    [[10,2,0],
     [1,0,2]],
    
    [[5,8,0],
     [2,7,0]],
    
    [[2,1,9],
     [4,-3,32]]],
     [[[1,2,0],
     [3,5,-1]],
    
    [[10,2,0],
     [1,0,2]],
    
    [[5,8,0],
     [2,7,0]],
    
    [[2,1,9],
     [4,-3,32]]]
], dtype=tf.float32)
print(tensor_four_d.shape)
print(tensor_four_d.ndim)
print(tensor_four_d)

(2, 4, 2, 3)
4
tf.Tensor(
[[[[ 1.  2.  0.]
   [ 3.  5. -1.]]

  [[10.  2.  0.]
   [ 1.  0.  2.]]

  [[ 5.  8.  0.]
   [ 2.  7.  0.]]

  [[ 2.  1.  9.]
   [ 4. -3. 32.]]]


 [[[ 1.  2.  0.]
   [ 3.  5. -1.]]

  [[10.  2.  0.]
   [ 1.  0.  2.]]

  [[ 5.  8.  0.]
   [ 2.  7.  0.]]

  [[ 2.  1.  9.]
   [ 4. -3. 32.]]]], shape=(2, 4, 2, 3), dtype=float32)


In [7]:
import numpy as np

In [8]:
casted_tensor_one_d = tf.cast(tensor_one_d, dtype=tf.bool)
print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)
tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)


In [9]:
tensor_bool = tf.constant([True, True, False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [10]:
casted_string = tf.constant(["hello world", "hi"])

In [11]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [12]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int32)


In [13]:
eye_tensor = tf.eye(num_rows=5, num_columns=3, dtype=tf.bool, batch_shape=[2,2])
print(eye_tensor)

tf.Tensor(
[[[[ True False False]
   [False  True False]
   [False False  True]
   [False False False]
   [False False False]]

  [[ True False False]
   [False  True False]
   [False False  True]
   [False False False]
   [False False False]]]


 [[[ True False False]
   [False  True False]
   [False False  True]
   [False False False]
   [False False False]]

  [[ True False False]
   [False  True False]
   [False False  True]
   [False False False]
   [False False False]]]], shape=(2, 2, 5, 3), dtype=bool)


In [14]:
fill_tensor = tf.fill([1,3,4],5, name=None)
fill_tensor

<tf.Tensor: shape=(1, 3, 4), dtype=int32, numpy=
array([[[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]])>

In [15]:
ones_tensor = tf.ones([5,3], dtype=tf.float32)
ones_tensor

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [16]:
ones_like_tensor = tf.ones_like(fill_tensor)

In [17]:
fill_tensor

<tf.Tensor: shape=(1, 3, 4), dtype=int32, numpy=
array([[[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]])>

In [18]:
ones_like_tensor

<tf.Tensor: shape=(1, 3, 4), dtype=int32, numpy=
array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])>

In [19]:
zeros_tensor = tf.zeros([3,2], dtype=tf.float32)
zeros_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [20]:
tensor_three_d.shape

TensorShape([4, 2, 3])

In [21]:
tf.shape(tensor_three_d)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 2, 3])>

In [22]:
tf.rank(tensor_three_d)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [23]:
t = tf.constant([[1,1,1], [2,2,2], [3,3,3], [4,4,4]])
tf.rank(t)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [24]:
tf.size(t)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [25]:
t_2 = tf.constant([[1,1,1], [2,2,2]])
tf.size(t_2, out_type=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [58]:
# stddev: σ
random_tensor = tf.random.normal([3,2], stddev=1.0, mean=144.0, dtype=tf.float32)
random_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[142.90358, 144.45447],
       [142.56549, 145.59782],
       [143.29736, 143.14458]], dtype=float32)>

In [317]:
random_tensor = tf.random.uniform([5,3], minval=0, maxval=5, dtype=tf.int32, seed=10)
random_tensor

<tf.Tensor: shape=(5, 3), dtype=int32, numpy=
array([[3, 3, 4],
       [3, 3, 4],
       [1, 0, 1],
       [3, 3, 0],
       [0, 1, 4]])>

In [323]:
tf.random.set_seed(5)
print(tf.random.uniform([3,], minval=0, maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform([3,], minval=0, maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform([3,], minval=0, maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform([3,], minval=0, maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform([3,], minval=0, maxval=5, dtype=tf.int32, seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)
tf.Tensor([4 2 2], shape=(3,), dtype=int32)


In [326]:
tf.random.set_seed(5)
print(tf.random.uniform([3,], minval=0, maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform([3,], minval=0, maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform([3,], minval=0, maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform([3,], minval=0, maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform([3,], minval=0, maxval=5, dtype=tf.int32, seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)
tf.Tensor([4 2 2], shape=(3,), dtype=int32)


## 1.2 Tensor Indexing

In [17]:
tensor_indexed = tf.constant([3,6,2,4,6,66,7])
tf.print(tensor_indexed[0])
tf.print(tensor_indexed[0:4])
tf.print(tensor_indexed[1:6:1])

min_index = 1
max_index = 4
step = 1
tf.print(tensor_indexed[min_index:max_index:step])

3
[3 6 2 4]
[6 2 4 6 66]
[6 2 4]


In [18]:
tensor_indexed[3:-1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4,  6, 66])>

In [32]:
tensor_two_d = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12],
])

# ROWS , COLS
print(tensor_two_d[2,2])
print(tensor_two_d[2,1:])
print(tensor_two_d[1:3,0])
print(tensor_two_d[..., 2])

tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor([8 9], shape=(2,), dtype=int32)
tf.Tensor([4 7], shape=(2,), dtype=int32)
tf.Tensor([ 3  6  9 12], shape=(4,), dtype=int32)


In [50]:
tensor_three_d = tf.constant([
    [[1,2,3], [4,5,6], [7,8,9]],
    [[10,11,12], [13,14,15], [16,17,18]],
    [[19,20,21], [22,23,24], [25,26,27]],
])

In [46]:
print(tensor_three_d[0, 1, 1])

tf.Tensor(5, shape=(), dtype=int32)


In [47]:
print(tensor_three_d[0:2, 1, 0])

tf.Tensor([ 4 13], shape=(2,), dtype=int32)


In [48]:
print(tensor_three_d[0, :, :])

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [49]:
print(tensor_three_d[0:2, : , 2])

tf.Tensor(
[[ 3  6  9]
 [12 15 18]], shape=(2, 3), dtype=int32)


# 2. Math Operations

In [55]:
x_ab = tf.abs(tf.constant([-2.25, 3.25]))
x_ab

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [60]:
x_abs_complex = tf.constant([-2.25 + 4.75j])
tf.abs(x_abs_complex)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([5.25594901])>

In [66]:
tf.sqrt((-2.25)**2 + 4.75**2)

<tf.Tensor: shape=(), dtype=float32, numpy=5.255949>