## 1. Import Dependencies

In [1]:
import tensorflow as tf

## 1.1 Introductions to tensors

In [2]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
tensor_one_d = tf.constant([2,0,-3,8,90.])
print(tensor_one_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)


In [4]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d)
print(tensor_two_d.shape)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)
(4, 3)


In [5]:
tensor_three_d = tf.constant([
    [[1,2,0],
     [3,5,-1]],
    
    [[10,2,0],
     [1,0,2]],
    
    [[5,8,0],
     [2,7,0]],
    
    [[2,1,9],
     [4,-3,32]]
])
print(tensor_three_d)
print(tensor_three_d.ndim)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)
3


In [6]:
tensor_four_d = tf.constant([
    [[[1,2,0],
     [3,5,-1]],
    
    [[10,2,0],
     [1,0,2]],
    
    [[5,8,0],
     [2,7,0]],
    
    [[2,1,9],
     [4,-3,32]]],
     [[[1,2,0],
     [3,5,-1]],
    
    [[10,2,0],
     [1,0,2]],
    
    [[5,8,0],
     [2,7,0]],
    
    [[2,1,9],
     [4,-3,32]]]
], dtype=tf.float32)
print(tensor_four_d.shape)
print(tensor_four_d.ndim)
print(tensor_four_d)

(2, 4, 2, 3)
4
tf.Tensor(
[[[[ 1.  2.  0.]
   [ 3.  5. -1.]]

  [[10.  2.  0.]
   [ 1.  0.  2.]]

  [[ 5.  8.  0.]
   [ 2.  7.  0.]]

  [[ 2.  1.  9.]
   [ 4. -3. 32.]]]


 [[[ 1.  2.  0.]
   [ 3.  5. -1.]]

  [[10.  2.  0.]
   [ 1.  0.  2.]]

  [[ 5.  8.  0.]
   [ 2.  7.  0.]]

  [[ 2.  1.  9.]
   [ 4. -3. 32.]]]], shape=(2, 4, 2, 3), dtype=float32)


In [7]:
import numpy as np

In [8]:
casted_tensor_one_d = tf.cast(tensor_one_d, dtype=tf.bool)
print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)
tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)


In [9]:
tensor_bool = tf.constant([True, True, False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [10]:
casted_string = tf.constant(["hello world", "hi"])

In [11]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [12]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int32)


In [13]:
eye_tensor = tf.eye(num_rows=5, num_columns=3, dtype=tf.bool, batch_shape=[2,2])
print(eye_tensor)

tf.Tensor(
[[[[ True False False]
   [False  True False]
   [False False  True]
   [False False False]
   [False False False]]

  [[ True False False]
   [False  True False]
   [False False  True]
   [False False False]
   [False False False]]]


 [[[ True False False]
   [False  True False]
   [False False  True]
   [False False False]
   [False False False]]

  [[ True False False]
   [False  True False]
   [False False  True]
   [False False False]
   [False False False]]]], shape=(2, 2, 5, 3), dtype=bool)


In [14]:
fill_tensor = tf.fill([1,3,4],5, name=None)
fill_tensor

<tf.Tensor: shape=(1, 3, 4), dtype=int32, numpy=
array([[[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]])>

In [15]:
ones_tensor = tf.ones([5,3], dtype=tf.float32)
ones_tensor

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [16]:
ones_like_tensor = tf.ones_like(fill_tensor)

In [17]:
fill_tensor

<tf.Tensor: shape=(1, 3, 4), dtype=int32, numpy=
array([[[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]])>

In [18]:
ones_like_tensor

<tf.Tensor: shape=(1, 3, 4), dtype=int32, numpy=
array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])>

In [19]:
zeros_tensor = tf.zeros([3,2], dtype=tf.float32)
zeros_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [20]:
tensor_three_d.shape

TensorShape([4, 2, 3])

In [21]:
tf.shape(tensor_three_d)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 2, 3])>

In [22]:
tf.rank(tensor_three_d)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [23]:
t = tf.constant([[1,1,1], [2,2,2], [3,3,3], [4,4,4]])
tf.rank(t)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [24]:
tf.size(t)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [25]:
t_2 = tf.constant([[1,1,1], [2,2,2]])
tf.size(t_2, out_type=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [26]:
# stddev: σ
random_tensor = tf.random.normal([3,2], stddev=1.0, mean=144.0, dtype=tf.float32)
random_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[145.06232, 143.79279],
       [142.76295, 142.19276],
       [145.15988, 142.54611]], dtype=float32)>

In [27]:
random_tensor = tf.random.uniform([5,3], minval=0, maxval=5, dtype=tf.int32, seed=10)
random_tensor

<tf.Tensor: shape=(5, 3), dtype=int32, numpy=
array([[0, 2, 0],
       [2, 2, 2],
       [3, 0, 4],
       [0, 2, 3],
       [0, 1, 4]])>

In [28]:
tf.random.set_seed(5)
print(tf.random.uniform([3,], minval=0, maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform([3,], minval=0, maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform([3,], minval=0, maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform([3,], minval=0, maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform([3,], minval=0, maxval=5, dtype=tf.int32, seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)
tf.Tensor([4 2 2], shape=(3,), dtype=int32)


In [29]:
tf.random.set_seed(5)
print(tf.random.uniform([3,], minval=0, maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform([3,], minval=0, maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform([3,], minval=0, maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform([3,], minval=0, maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform([3,], minval=0, maxval=5, dtype=tf.int32, seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)
tf.Tensor([4 2 2], shape=(3,), dtype=int32)


## 1.2 Tensor Indexing

In [30]:
tensor_indexed = tf.constant([3,6,2,4,6,66,7])
tf.print(tensor_indexed[0])
tf.print(tensor_indexed[0:4])
tf.print(tensor_indexed[1:6:1])

min_index = 1
max_index = 4
step = 1
tf.print(tensor_indexed[min_index:max_index:step])

3
[3 6 2 4]
[6 2 4 6 66]
[6 2 4]


In [31]:
tensor_indexed[3:-1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4,  6, 66])>

In [32]:
tensor_two_d = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12],
])

# ROWS , COLS
print(tensor_two_d[2,2])
print(tensor_two_d[2,1:])
print(tensor_two_d[1:3,0])
print(tensor_two_d[..., 2])

tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor([8 9], shape=(2,), dtype=int32)
tf.Tensor([4 7], shape=(2,), dtype=int32)
tf.Tensor([ 3  6  9 12], shape=(4,), dtype=int32)


In [33]:
tensor_three_d = tf.constant([
    [[1,2,3], [4,5,6], [7,8,9]],
    [[10,11,12], [13,14,15], [16,17,18]],
    [[19,20,21], [22,23,24], [25,26,27]],
])

In [34]:
print(tensor_three_d[0, 1, 1])

tf.Tensor(5, shape=(), dtype=int32)


In [35]:
print(tensor_three_d[0:2, 1, 0])

tf.Tensor([ 4 13], shape=(2,), dtype=int32)


In [36]:
print(tensor_three_d[0, :, :])

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [37]:
print(tensor_three_d[0:2, : , 2])

tf.Tensor(
[[ 3  6  9]
 [12 15 18]], shape=(2, 3), dtype=int32)


# 2. Math Operations

In [38]:
x_ab = tf.abs(tf.constant([-2.25, 3.25]))
x_ab

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [39]:
x_abs_complex = tf.constant([-2.25 + 4.75j])
tf.abs(x_abs_complex)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([5.25594901])>

In [40]:
tf.sqrt((-2.25)**2 + 4.75**2)

<tf.Tensor: shape=(), dtype=float32, numpy=5.255949>

In [41]:
x_1 = tf.constant([5,3,6,6,4,6], dtype=tf.float32)
x_2 = tf.constant([7,6,2,6,7,11], dtype=tf.float32)

print(tf.add(x_1, x_2))
print(tf.minimum(x_1, x_2))
print(tf.multiply(x_1, x_2))
print(tf.divide(x_1, x_2))
print(tf.math.divide_no_nan(x_1, x_2))

tf.Tensor([12.  9.  8. 12. 11. 17.], shape=(6,), dtype=float32)
tf.Tensor([5. 3. 2. 6. 4. 6.], shape=(6,), dtype=float32)
tf.Tensor([35. 18. 12. 36. 28. 66.], shape=(6,), dtype=float32)
tf.Tensor([0.71428573 0.5        3.         1.         0.5714286  0.54545456], shape=(6,), dtype=float32)
tf.Tensor([0.71428573 0.5        3.         1.         0.5714286  0.54545456], shape=(6,), dtype=float32)


In [42]:
x_1 = tf.constant([[5,3,6,6,4,6], [5,45,65,5,3,4]], dtype=tf.float32)
x_2 = tf.constant([7], dtype=tf.float32)
x_2_stretched = tf.constant([7,7,7,7,7,7], dtype=tf.float32)

print(tf.math.add(x_1, x_2))
print(tf.math.add(x_1, x_2_stretched))

tf.Tensor(
[[12. 10. 13. 13. 11. 13.]
 [12. 52. 72. 12. 10. 11.]], shape=(2, 6), dtype=float32)
tf.Tensor(
[[12. 10. 13. 13. 11. 13.]
 [12. 52. 72. 12. 10. 11.]], shape=(2, 6), dtype=float32)


In [43]:
x_1 = tf.constant([[5,3,6,6,4,6]], dtype=tf.float32)
x_2 = tf.constant([[7], [5], [3]], dtype=tf.float32)

print(x_1.shape)
print(x_2.shape)
print(tf.math.multiply(x_1, x_2))

(1, 6)
(3, 1)
tf.Tensor(
[[35. 21. 42. 42. 28. 42.]
 [25. 15. 30. 30. 20. 30.]
 [15.  9. 18. 18. 12. 18.]], shape=(3, 6), dtype=float32)


In [44]:
x_argmax = tf.constant([
    [2, 20, 30, 3, 6],
    [3, 11, 16, 1, 8],
    [14, 45, 23, 5, 27]
])

# 0 COLUMNS
# 1 ROWS
print(tf.math.argmax(x_argmax, 0))
print(tf.math.argmax(x_argmax, 1))

tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)
tf.Tensor([2 2 1], shape=(3,), dtype=int64)


In [45]:
x_argmax = tf.constant([
    [200,1250,130,3,6],
    [3,11,2404,2540,2043]
])

print(tf.math.argmin(x_argmax))
print(tf.math.argmax(x_argmax))

tf.Tensor([1 1 0 0 0], shape=(5,), dtype=int64)
tf.Tensor([0 0 1 1 1], shape=(5,), dtype=int64)


In [46]:
x = tf.constant([[2,2], [3,3]])
y = tf.constant([[3,0], [1,4]])

tf.pow(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 8,  1],
       [ 3, 81]])>

In [47]:
tf.pow(tf.constant(2), tf.constant(3))

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [48]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,100],
    [1,5,6],
    [2,3,8],
], dtype=tf.float16)

tensor_two_d.shape

TensorShape([4, 3])

In [49]:
tf.math.reduce_sum(tensor_two_d, axis=0)

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([  7.,  15., 114.], dtype=float16)>

In [50]:
tf.math.reduce_sum(tensor_two_d, axis=1)

<tf.Tensor: shape=(4,), dtype=float16, numpy=array([  3., 108.,  12.,  13.], dtype=float16)>

In [51]:
tf.math.reduce_std(tensor_two_d, axis=0, keepdims=True)

<tf.Tensor: shape=(1, 3), dtype=float16, numpy=array([[ 0.829,  1.299, 41.38 ]], dtype=float16)>

In [52]:
tf.math.sigmoid([0.0, 1.0, 50.0, 100.0])

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.5       , 0.73105854, 1.        , 1.        ], dtype=float32)>

In [53]:
tf.math.top_k(tensor_two_d, k=3, sorted=True)

TopKV2(values=<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[  2.,   1.,   0.],
       [100.,   5.,   3.],
       [  6.,   5.,   1.],
       [  8.,   3.,   2.]], dtype=float16)>, indices=<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[1, 0, 2],
       [2, 1, 0],
       [2, 1, 0],
       [2, 1, 0]])>)

In [54]:
x_1 = tf.constant([
    [1, 2, 0],
    [1, 2, 0],  # Adjusted to have the same number of elements as the first row
])

x_2 = tf.constant([
    [1, 2, 0, 2],
    [3, 5, -1, 2],
    [4, 5, 6, 0],
])

x_3 = tf.constant([
    [1, 2, 0, 2],
    [3, 5, -1, 2],
])


x_1.shape, x_2.shape

(TensorShape([2, 3]), TensorShape([3, 4]))

In [55]:
tf.linalg.matmul(x_1, x_2)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 7, 12, -2,  6],
       [ 7, 12, -2,  6]])>

In [56]:
x_1@x_2

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 7, 12, -2,  6],
       [ 7, 12, -2,  6]])>

In [57]:
x_1_tranpose = tf.transpose(x_1)
x_1_tranpose, x_1

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 1],
        [2, 2],
        [0, 0]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 0],
        [1, 2, 0]])>)

In [58]:
print(x_1.shape, x_2.shape, x_3.shape, tf.transpose(x_2).shape)
# tf.linalg.matmul(x_1, x_2, transpose_a=False, transpose_b=True)

(2, 3) (3, 4) (2, 4) (4, 3)


In [59]:
tf.linalg.matmul(x_2, x_3, transpose_a=False, transpose_b=True)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 9, 17],
       [17, 39],
       [14, 31]])>

In [60]:
x_2@tf.transpose(x_3)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 9, 17],
       [17, 39],
       [14, 31]])>

In [61]:
# x_3.T = 4,2
# x_2.T = 4,3
x_2_T = tf.constant([
    [1,2],
    [3,5],
    [4,5]
])

tf.linalg.matmul(tf.transpose(x_3), x_2, transpose_a=True, transpose_b=True)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 9, 17, 14],
       [17, 39, 31]])>

In [62]:
x_1 = tf.constant([
    [[1,2],
     [3,5]],
    
    [[10,2],
     [1,0]],
    
    [[5,8],
     [2,7]],
    
    [[2,1],
     [4,-3]]
])

x_2 = tf.constant([
    [[5,1,4],
     [34,15,1]],
    
    [[10,2,0],
     [1,0,2]],
    
    [[5,8,0],
     [2,7,0]],
    
    [[2,1,9],
     [4,-3,32]]
])

x_1.shape, x_2.shape

(TensorShape([4, 2, 2]), TensorShape([4, 2, 3]))

In [63]:
tf.linalg.matmul(x_1, x_2)

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[ 73,  31,   6],
        [185,  78,  17]],

       [[102,  20,   4],
        [ 10,   2,   0]],

       [[ 41,  96,   0],
        [ 24,  65,   0]],

       [[  8,  -1,  50],
        [ -4,  13, -60]]])>

In [64]:
x_1 = tf.constant([
    [10,0],
    [1,2]
])

x_2 = tf.constant([
    [1,2,2],
    [5,3,2]
])

x_1.shape, x_2.shape

(TensorShape([2, 2]), TensorShape([2, 3]))

In [65]:
tf.linalg.matmul(x_1, x_2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 20, 20],
       [11,  8,  6]])>

In [66]:
x_1 = tf.constant([
    [0,0],
    [0,2]
])

x_2 = tf.constant([
    [1,0,0],
    [0,0,0]
])

# Improves computation since mostly filled with zeros
tf.linalg.matmul(x_1, x_2, a_is_sparse=True, b_is_sparse=True)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]])>

In [67]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,100],
    [1,5,6],
    [2,3,8]
])

# (m-n <= lower) and (n-m <= upper)
# m -- rows, n -- columns
# if both conditions are true, the value of the number is conserved otherwise it is a 0
tf.linalg.band_part(tensor_two_d, 0, -1)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[  1,   2,   0],
       [  0,   5, 100],
       [  0,   0,   6],
       [  0,   0,   0]])>

In [68]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,100],
    [1,5,6],
], dtype=tf.float32)

tensor_two_d_inv = tf.linalg.inv(tensor_two_d)

In [69]:
tensor_two_d_inv

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.5359477 ,  0.03921569, -0.6535948 ],
       [-0.26797384, -0.01960784,  0.3267974 ],
       [-0.03267974,  0.00980392,  0.00326797]], dtype=float32)>

In [70]:
tensor_two_d@tensor_two_d_inv

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  9.9999994e-01, -8.9406967e-08],
       [ 0.0000000e+00, -3.7252903e-09,  1.0000000e+00]], dtype=float32)>

In [71]:
s,u,v = tf.linalg.svd(tensor_two_d)

In [72]:
s

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([100.366394 ,   5.2198477,   0.5840839], dtype=float32)>

In [73]:
u

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.00135705,  0.41529003, -0.90968823],
       [-0.99803734, -0.05751525, -0.02476798],
       [-0.06260682,  0.9078691 ,  0.41455284]], dtype=float32)>

In [74]:
v

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.03046915,  0.22043042, -0.97492665],
       [-0.0528658 ,  0.9736589 ,  0.22179599],
       [-0.9981367 , -0.05829822,  0.01801333]], dtype=float32)>

# 3. Expansion and Squeezing

In [75]:
tensor_three_d = tf.constant([
    [[1,2,0],
     [3,5,-1]],
    
    [[10,2,0],
     [1,0,2]],
    
    [[5,8,0],
     [2,7,0]],
    
    [[2,1,9],
     [4,-3,32]]
])

print(tensor_three_d.shape)
print(tf.expand_dims(tensor_three_d, axis=0).shape)
print(tf.expand_dims(tensor_three_d, axis=1).shape)

(4, 2, 3)
(1, 4, 2, 3)
(4, 1, 2, 3)


In [76]:
x = tf.constant([2,3,4,5])
print(x.shape)
print(tf.expand_dims(x, axis=1).shape)

(4,)
(4, 1)


In [77]:
x_expanded = tf.expand_dims(x, axis=0)
x_expanded

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[2, 3, 4, 5]])>

In [78]:
x_squeezed = tf.squeeze(x_expanded, axis=0)
for i in range(2):
    x_squeezed = tf.squeeze(x_expanded, axis=0)
    
x_squeezed

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([2, 3, 4, 5])>

In [79]:
x_expanded_2 = tf.expand_dims(tensor_three_d, axis=3)
tf.squeeze(x_expanded_2, axis=3)

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  0],
        [ 3,  5, -1]],

       [[10,  2,  0],
        [ 1,  0,  2]],

       [[ 5,  8,  0],
        [ 2,  7,  0]],

       [[ 2,  1,  9],
        [ 4, -3, 32]]])>

In [80]:
tf.reshape(x_expanded_2, [4,2,3])


<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  0],
        [ 3,  5, -1]],

       [[10,  2,  0],
        [ 1,  0,  2]],

       [[ 5,  8,  0],
        [ 2,  7,  0]],

       [[ 2,  1,  9],
        [ 4, -3, 32]]])>

In [81]:
x_reshape = tf.constant([
    [3,5,6,6],
    [4,6,-1,2],
])

tf.reshape(x_reshape, [4, 2])

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 3,  5],
       [ 6,  6],
       [ 4,  6],
       [-1,  2]])>

In [82]:
# -1 means that tensorflow will automatically get its shape
tf.reshape(x_reshape, [4,-1])

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 3,  5],
       [ 6,  6],
       [ 4,  6],
       [-1,  2]])>

In [83]:
tf.reshape(x_reshape, [-1])

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([ 3,  5,  6,  6,  4,  6, -1,  2])>

In [84]:
t1 = [[[1, 2, 3],
      [4, 5, 6]]]

t2 = [[[7, 8, 9],
      [10, 11, 12]]]

print(tf.constant(t1).shape)
print(tf.constant(t2).shape)

(1, 2, 3)
(1, 2, 3)


In [85]:
t3 = tf.concat([t1, t2], axis=0)
t3, t3.shape

(<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]])>,
 TensorShape([2, 2, 3]))

In [86]:
t3 = tf.concat([t1, t2], axis=1)
t3, t3.shape

(<tf.Tensor: shape=(1, 4, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]])>,
 TensorShape([1, 4, 3]))

In [87]:
tf.stack([t1,t2], axis=0)

<tf.Tensor: shape=(2, 1, 2, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6]]],


       [[[ 7,  8,  9],
         [10, 11, 12]]]])>

In [88]:
tf.stack([t1,t2,t1], axis=0)

<tf.Tensor: shape=(3, 1, 2, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6]]],


       [[[ 7,  8,  9],
         [10, 11, 12]]],


       [[[ 1,  2,  3],
         [ 4,  5,  6]]]])>

In [89]:
tf.stack([t1,t2, t1], axis=1)

<tf.Tensor: shape=(1, 3, 2, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]],

        [[ 1,  2,  3],
         [ 4,  5,  6]]]])>

In [90]:
tf.stack([t1, t2, t1], axis=2)

<tf.Tensor: shape=(1, 2, 3, 3), dtype=int32, numpy=
array([[[[ 1,  2,  3],
         [ 7,  8,  9],
         [ 1,  2,  3]],

        [[ 4,  5,  6],
         [10, 11, 12],
         [ 4,  5,  6]]]])>

In [91]:
t1 = [[1,2,3],
      [4,5,6],
      [5,6,2],
      [1,2,1]]

t2 = [[7,8,9],
      [10,11,12],
      [0,0,-2],
      [-1,5,2]]

print(tf.constant(t1).shape)
print(tf.constant(t2).shape)

(4, 3)
(4, 3)


In [92]:
tf.stack([t1, t2], axis=0)

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 5,  6,  2],
        [ 1,  2,  1]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [ 0,  0, -2],
        [-1,  5,  2]]])>

In [93]:
tf.stack([t1, t2], axis=1)

<tf.Tensor: shape=(4, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[ 4,  5,  6],
        [10, 11, 12]],

       [[ 5,  6,  2],
        [ 0,  0, -2]],

       [[ 1,  2,  1],
        [-1,  5,  2]]])>

In [94]:
# 1,4,3 - 1,4,3 --> 2,4,3
tf.concat([tf.expand_dims(t, axis=0) for t in [t1, t2]], axis=0)

<tf.Tensor: shape=(2, 4, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 5,  6,  2],
        [ 1,  2,  1]],

       [[ 7,  8,  9],
        [10, 11, 12],
        [ 0,  0, -2],
        [-1,  5,  2]]])>

In [95]:
t = tf.constant([[1,2,3], [4,5,6]])

# (top and bottom) - (left and right)
paddings = tf.constant([[1,1], [2,2]])

tf.pad(t, paddings, 'CONSTANT', constant_values=0)

<tf.Tensor: shape=(4, 7), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 0, 0],
       [0, 0, 4, 5, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 0]])>

In [96]:
params = tf.constant(['p0', 'p1', 'p2', 'p3', 'p4', 'p5'])
params[0].numpy()
params[1:3+1].numpy()

array([b'p1', b'p2', b'p3'], dtype=object)

In [97]:
tf.gather(params, [1,2,3])

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [98]:
tf.gather(params, tf.range(1,4))

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p1', b'p2', b'p3'], dtype=object)>

In [99]:
tf.gather(params, [0,5,3])

<tf.Tensor: shape=(3,), dtype=string, numpy=array([b'p0', b'p5', b'p3'], dtype=object)>

In [104]:
params = tf.constant([
    [[0, 1.0, 2.0],
     [10.0, 11.0, 12.0],
     [20.0, 21.0, 22.0],
     [30.0, 31.0, 32.0]],
])

print(params.shape)
tf.gather(params, [2, 0], axis=0)

(1, 4, 3)


<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[20., 21., 22.],
        [ 0.,  1.,  2.]]], dtype=float32)>

In [105]:
tf.gather(params, [2, 0], axis=1)

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[20., 21., 22.],
        [ 0.,  1.,  2.]]], dtype=float32)>

In [106]:
params = tf.constant([
    [[0, 1.0, 2.0],
     [10.0, 11.0, 12.0],
     [20.0, 21.0, 22.0],
     [30.0, 31.0, 32.0]],
    
    [[3, 1.0, 21],
     [1, 3, 88],
     [0, 5, 55],
     [0, 2, 30]]
])

tf.gather(params, [2, 0], axis=1)

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[20., 21., 22.],
        [ 0.,  1.,  2.]],

       [[ 0.,  5., 55.],
        [ 3.,  1., 21.]]], dtype=float32)>

In [108]:
tf.gather(params, [2, 0], axis=0)

<tf.Tensor: shape=(2, 4, 3), dtype=float32, numpy=
array([[[ 3.,  1., 21.],
        [ 1.,  3., 88.],
        [ 0.,  5., 55.],
        [ 0.,  2., 30.]],

       [[ 0.,  1.,  2.],
        [10., 11., 12.],
        [20., 21., 22.],
        [30., 31., 32.]]], dtype=float32)>

In [110]:
tf.gather(params, [1, 0], axis=1)

<tf.Tensor: shape=(2, 2, 3), dtype=float32, numpy=
array([[[10., 11., 12.],
        [ 0.,  1.,  2.]],

       [[ 1.,  3., 88.],
        [ 3.,  1., 21.]]], dtype=float32)>

In [123]:
indices = [
    [2,1],
]

params = [['a', 'b'],
          ['c', 'd'],
          ['e', 'f']]

tf.gather_nd(params, indices)

<tf.Tensor: shape=(1,), dtype=string, numpy=array([b'f'], dtype=object)>

In [127]:
tf.gather(params, indices, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=string, numpy=
array([[[b'e', b'f'],
        [b'c', b'd']]], dtype=object)>

In [138]:
indices = [[0, 1], [1, 0]]
params = [ 
  [['a0', 'b0'],
  ['c0', 'd0']],
  
  [['a1', 'b1'],
    ['c1', 'd1']]
]

tf.gather_nd(params, indices)

<tf.Tensor: shape=(2, 2), dtype=string, numpy=
array([[b'c0', b'd0'],
       [b'a1', b'b1']], dtype=object)>

In [139]:
indices = [
    [[0, 1],
     [1, 0]],
    
    [[0, 0],
     [1, 1]]
]

params = [
    [['a0', 'b0'],
     ['c0', 'd0']],
    
    [['a1', 'b1'],
     ['c1', 'd1']]
]
tf.gather_nd(params, indices)

<tf.Tensor: shape=(2, 2, 2), dtype=string, numpy=
array([[[b'c0', b'd0'],
        [b'a1', b'b1']],

       [[b'a0', b'b0'],
        [b'c1', b'd1']]], dtype=object)>