## 1. Import Dependencies

In [113]:
import tensorflow as tf

## 1.1 Introductions to tensors

In [114]:
tensor_zero_d = tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [115]:
tensor_one_d = tf.constant([2,0,-3,8,90.])
print(tensor_one_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)


In [116]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,-1],
    [1,5,6],
    [2,3,8]
])
print(tensor_two_d)
print(tensor_two_d.shape)

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]
 [ 1  5  6]
 [ 2  3  8]], shape=(4, 3), dtype=int32)
(4, 3)


In [117]:
tensor_three_d = tf.constant([
    [[1,2,0],
     [3,5,-1]],
    
    [[10,2,0],
     [1,0,2]],
    
    [[5,8,0],
     [2,7,0]],
    
    [[2,1,9],
     [4,-3,32]]
])
print(tensor_three_d)
print(tensor_three_d.ndim)

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)
3


In [118]:
tensor_four_d = tf.constant([
    [[[1,2,0],
     [3,5,-1]],
    
    [[10,2,0],
     [1,0,2]],
    
    [[5,8,0],
     [2,7,0]],
    
    [[2,1,9],
     [4,-3,32]]],
     [[[1,2,0],
     [3,5,-1]],
    
    [[10,2,0],
     [1,0,2]],
    
    [[5,8,0],
     [2,7,0]],
    
    [[2,1,9],
     [4,-3,32]]]
], dtype=tf.float32)
print(tensor_four_d.shape)
print(tensor_four_d.ndim)
print(tensor_four_d)

(2, 4, 2, 3)
4
tf.Tensor(
[[[[ 1.  2.  0.]
   [ 3.  5. -1.]]

  [[10.  2.  0.]
   [ 1.  0.  2.]]

  [[ 5.  8.  0.]
   [ 2.  7.  0.]]

  [[ 2.  1.  9.]
   [ 4. -3. 32.]]]


 [[[ 1.  2.  0.]
   [ 3.  5. -1.]]

  [[10.  2.  0.]
   [ 1.  0.  2.]]

  [[ 5.  8.  0.]
   [ 2.  7.  0.]]

  [[ 2.  1.  9.]
   [ 4. -3. 32.]]]], shape=(2, 4, 2, 3), dtype=float32)


In [119]:
import numpy as np

In [120]:
casted_tensor_one_d = tf.cast(tensor_one_d, dtype=tf.bool)
print(tensor_one_d)
print(casted_tensor_one_d)

tf.Tensor([ 2.  0. -3.  8. 90.], shape=(5,), dtype=float32)
tf.Tensor([ True False  True  True  True], shape=(5,), dtype=bool)


In [121]:
tensor_bool = tf.constant([True, True, False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [122]:
casted_string = tf.constant(["hello world", "hi"])

In [123]:
np_array = np.array([1,2,4])
print(np_array)

[1 2 4]


In [124]:
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

tf.Tensor([1 2 4], shape=(3,), dtype=int32)


In [125]:
eye_tensor = tf.eye(num_rows=5, num_columns=3, dtype=tf.bool, batch_shape=[2,2])
print(eye_tensor)

tf.Tensor(
[[[[ True False False]
   [False  True False]
   [False False  True]
   [False False False]
   [False False False]]

  [[ True False False]
   [False  True False]
   [False False  True]
   [False False False]
   [False False False]]]


 [[[ True False False]
   [False  True False]
   [False False  True]
   [False False False]
   [False False False]]

  [[ True False False]
   [False  True False]
   [False False  True]
   [False False False]
   [False False False]]]], shape=(2, 2, 5, 3), dtype=bool)


In [126]:
fill_tensor = tf.fill([1,3,4],5, name=None)
fill_tensor

<tf.Tensor: shape=(1, 3, 4), dtype=int32, numpy=
array([[[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]])>

In [127]:
ones_tensor = tf.ones([5,3], dtype=tf.float32)
ones_tensor

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [128]:
ones_like_tensor = tf.ones_like(fill_tensor)

In [129]:
fill_tensor

<tf.Tensor: shape=(1, 3, 4), dtype=int32, numpy=
array([[[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]])>

In [130]:
ones_like_tensor

<tf.Tensor: shape=(1, 3, 4), dtype=int32, numpy=
array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])>

In [131]:
zeros_tensor = tf.zeros([3,2], dtype=tf.float32)
zeros_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [132]:
tensor_three_d.shape

TensorShape([4, 2, 3])

In [133]:
tf.shape(tensor_three_d)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 2, 3])>

In [134]:
tf.rank(tensor_three_d)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [135]:
t = tf.constant([[1,1,1], [2,2,2], [3,3,3], [4,4,4]])
tf.rank(t)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [136]:
tf.size(t)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [137]:
t_2 = tf.constant([[1,1,1], [2,2,2]])
tf.size(t_2, out_type=tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [138]:
# stddev: σ
random_tensor = tf.random.normal([3,2], stddev=1.0, mean=144.0, dtype=tf.float32)
random_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[143.81969, 143.04971],
       [143.96036, 143.25746],
       [145.32315, 143.38145]], dtype=float32)>

In [139]:
random_tensor = tf.random.uniform([5,3], minval=0, maxval=5, dtype=tf.int32, seed=10)
random_tensor

<tf.Tensor: shape=(5, 3), dtype=int32, numpy=
array([[4, 2, 1],
       [0, 4, 0],
       [2, 0, 4],
       [1, 3, 3],
       [3, 1, 2]])>

In [140]:
tf.random.set_seed(5)
print(tf.random.uniform([3,], minval=0, maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform([3,], minval=0, maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform([3,], minval=0, maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform([3,], minval=0, maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform([3,], minval=0, maxval=5, dtype=tf.int32, seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)
tf.Tensor([4 2 2], shape=(3,), dtype=int32)


In [141]:
tf.random.set_seed(5)
print(tf.random.uniform([3,], minval=0, maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform([3,], minval=0, maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform([3,], minval=0, maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform([3,], minval=0, maxval=5, dtype=tf.int32, seed=10))
print(tf.random.uniform([3,], minval=0, maxval=5, dtype=tf.int32, seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)
tf.Tensor([4 2 2], shape=(3,), dtype=int32)


## 1.2 Tensor Indexing

In [142]:
tensor_indexed = tf.constant([3,6,2,4,6,66,7])
tf.print(tensor_indexed[0])
tf.print(tensor_indexed[0:4])
tf.print(tensor_indexed[1:6:1])

min_index = 1
max_index = 4
step = 1
tf.print(tensor_indexed[min_index:max_index:step])

3
[3 6 2 4]
[6 2 4 6 66]
[6 2 4]


In [143]:
tensor_indexed[3:-1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 4,  6, 66])>

In [144]:
tensor_two_d = tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12],
])

# ROWS , COLS
print(tensor_two_d[2,2])
print(tensor_two_d[2,1:])
print(tensor_two_d[1:3,0])
print(tensor_two_d[..., 2])

tf.Tensor(9, shape=(), dtype=int32)
tf.Tensor([8 9], shape=(2,), dtype=int32)
tf.Tensor([4 7], shape=(2,), dtype=int32)
tf.Tensor([ 3  6  9 12], shape=(4,), dtype=int32)


In [145]:
tensor_three_d = tf.constant([
    [[1,2,3], [4,5,6], [7,8,9]],
    [[10,11,12], [13,14,15], [16,17,18]],
    [[19,20,21], [22,23,24], [25,26,27]],
])

In [146]:
print(tensor_three_d[0, 1, 1])

tf.Tensor(5, shape=(), dtype=int32)


In [147]:
print(tensor_three_d[0:2, 1, 0])

tf.Tensor([ 4 13], shape=(2,), dtype=int32)


In [148]:
print(tensor_three_d[0, :, :])

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [149]:
print(tensor_three_d[0:2, : , 2])

tf.Tensor(
[[ 3  6  9]
 [12 15 18]], shape=(2, 3), dtype=int32)


# 2. Math Operations

In [150]:
x_ab = tf.abs(tf.constant([-2.25, 3.25]))
x_ab

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2.25, 3.25], dtype=float32)>

In [151]:
x_abs_complex = tf.constant([-2.25 + 4.75j])
tf.abs(x_abs_complex)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([5.25594901])>

In [152]:
tf.sqrt((-2.25)**2 + 4.75**2)

<tf.Tensor: shape=(), dtype=float32, numpy=5.255949>

In [153]:
x_1 = tf.constant([5,3,6,6,4,6], dtype=tf.float32)
x_2 = tf.constant([7,6,2,6,7,11], dtype=tf.float32)

print(tf.add(x_1, x_2))
print(tf.minimum(x_1, x_2))
print(tf.multiply(x_1, x_2))
print(tf.divide(x_1, x_2))
print(tf.math.divide_no_nan(x_1, x_2))

tf.Tensor([12.  9.  8. 12. 11. 17.], shape=(6,), dtype=float32)
tf.Tensor([5. 3. 2. 6. 4. 6.], shape=(6,), dtype=float32)
tf.Tensor([35. 18. 12. 36. 28. 66.], shape=(6,), dtype=float32)
tf.Tensor([0.71428573 0.5        3.         1.         0.5714286  0.54545456], shape=(6,), dtype=float32)
tf.Tensor([0.71428573 0.5        3.         1.         0.5714286  0.54545456], shape=(6,), dtype=float32)


In [154]:
x_1 = tf.constant([[5,3,6,6,4,6], [5,45,65,5,3,4]], dtype=tf.float32)
x_2 = tf.constant([7], dtype=tf.float32)
x_2_stretched = tf.constant([7,7,7,7,7,7], dtype=tf.float32)

print(tf.math.add(x_1, x_2))
print(tf.math.add(x_1, x_2_stretched))

tf.Tensor(
[[12. 10. 13. 13. 11. 13.]
 [12. 52. 72. 12. 10. 11.]], shape=(2, 6), dtype=float32)
tf.Tensor(
[[12. 10. 13. 13. 11. 13.]
 [12. 52. 72. 12. 10. 11.]], shape=(2, 6), dtype=float32)


In [155]:
x_1 = tf.constant([[5,3,6,6,4,6]], dtype=tf.float32)
x_2 = tf.constant([[7], [5], [3]], dtype=tf.float32)

print(x_1.shape)
print(x_2.shape)
print(tf.math.multiply(x_1, x_2))

(1, 6)
(3, 1)
tf.Tensor(
[[35. 21. 42. 42. 28. 42.]
 [25. 15. 30. 30. 20. 30.]
 [15.  9. 18. 18. 12. 18.]], shape=(3, 6), dtype=float32)


In [156]:
x_argmax = tf.constant([
    [2, 20, 30, 3, 6],
    [3, 11, 16, 1, 8],
    [14, 45, 23, 5, 27]
])

# 0 COLUMNS
# 1 ROWS
print(tf.math.argmax(x_argmax, 0))
print(tf.math.argmax(x_argmax, 1))

tf.Tensor([2 2 0 2 2], shape=(5,), dtype=int64)
tf.Tensor([2 2 1], shape=(3,), dtype=int64)


In [157]:
x_argmax = tf.constant([
    [200,1250,130,3,6],
    [3,11,2404,2540,2043]
])

print(tf.math.argmin(x_argmax))
print(tf.math.argmax(x_argmax))

tf.Tensor([1 1 0 0 0], shape=(5,), dtype=int64)
tf.Tensor([0 0 1 1 1], shape=(5,), dtype=int64)


In [158]:
x = tf.constant([[2,2], [3,3]])
y = tf.constant([[3,0], [1,4]])

tf.pow(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 8,  1],
       [ 3, 81]])>

In [159]:
tf.pow(tf.constant(2), tf.constant(3))

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [160]:
tensor_two_d = tf.constant([
    [1,2,0],
    [3,5,100],
    [1,5,6],
    [2,3,8],
], dtype=tf.float16)

tensor_two_d.shape

TensorShape([4, 3])

In [161]:
tf.math.reduce_sum(tensor_two_d, axis=0)

<tf.Tensor: shape=(3,), dtype=float16, numpy=array([  7.,  15., 114.], dtype=float16)>

In [162]:
tf.math.reduce_sum(tensor_two_d, axis=1)

<tf.Tensor: shape=(4,), dtype=float16, numpy=array([  3., 108.,  12.,  13.], dtype=float16)>

In [163]:
tf.math.reduce_std(tensor_two_d, axis=0, keepdims=True)

<tf.Tensor: shape=(1, 3), dtype=float16, numpy=array([[ 0.829,  1.299, 41.38 ]], dtype=float16)>

In [164]:
tf.math.sigmoid([0.0, 1.0, 50.0, 100.0])

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.5       , 0.73105854, 1.        , 1.        ], dtype=float32)>

In [165]:
tf.math.top_k(tensor_two_d, k=3, sorted=True)

TopKV2(values=<tf.Tensor: shape=(4, 3), dtype=float16, numpy=
array([[  2.,   1.,   0.],
       [100.,   5.,   3.],
       [  6.,   5.,   1.],
       [  8.,   3.,   2.]], dtype=float16)>, indices=<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[1, 0, 2],
       [2, 1, 0],
       [2, 1, 0],
       [2, 1, 0]])>)

In [175]:
x_1 = tf.constant([
    [1, 2, 0],
    [1, 2, 0],  # Adjusted to have the same number of elements as the first row
])

x_2 = tf.constant([
    [1, 2, 0, 2],
    [3, 5, -1, 2],
    [4, 5, 6, 0],
])

x_3 = tf.constant([
    [1, 2, 0, 2],
    [3, 5, -1, 2],
])


x_1.shape, x_2.shape

(TensorShape([2, 3]), TensorShape([3, 4]))

In [170]:
tf.linalg.matmul(x_1, x_2)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 7, 12, -2,  6],
       [ 7, 12, -2,  6]])>

In [171]:
x_1@x_2

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 7, 12, -2,  6],
       [ 7, 12, -2,  6]])>

In [172]:
x_1_tranpose = tf.transpose(x_1)
x_1_tranpose, x_1

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 1],
        [2, 2],
        [0, 0]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 0],
        [1, 2, 0]])>)

In [176]:
print(x_1.shape, x_2.shape, x_3.shape, tf.transpose(x_2).shape)
# tf.linalg.matmul(x_1, x_2, transpose_a=False, transpose_b=True)

(2, 3) (3, 4) (2, 4) (4, 3)


In [178]:
tf.linalg.matmul(x_2, x_3, transpose_a=False, transpose_b=True)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 9, 17],
       [17, 39],
       [14, 31]])>

In [179]:
x_2@tf.transpose(x_3)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 9, 17],
       [17, 39],
       [14, 31]])>