# Einsum Operator

# 1. Import Dependencies

In [1]:
import numpy as np

In [28]:
A = np.array([
    [2, 6, 5, 2],
    [2, -2, 2, 3],
    [1, 5, 4, 0],
])

B = np.array([
    [2, 9, 0, 3, 0],
    [3, 6, 8, -2, 2],
    [1, 3, 5, 0, 1],
    [3, 0, 2, 0, 5]
])

A.shape, B.shape

((3, 4), (4, 5))

In [29]:
np.matmul(A, B)

array([[33, 69, 77, -6, 27],
       [ 9, 12,  0, 10, 13],
       [21, 51, 60, -7, 14]])

In [30]:
np.einsum('ij,jk -> ik', A,B)

array([[33, 69, 77, -6, 27],
       [ 9, 12,  0, 10, 13],
       [21, 51, 60, -7, 14]])

In [32]:
C = np.array([
    [2, 6, 5, 2],
    [2, -2, 2, 3],
    [1, 5, 4, 0],
])

D = np.array([
    [2, 9, 0, 3],
    [3, 6, 8, -2],
    [1, 3, 5, 0],
])

print("Hardamond C := \n")
print(C*D, "\n")

print("Einsum C =: \n")
print(np.einsum('ij, ij -> ij', C,D))

Hardamond C := 

[[  4  54   0   6]
 [  6 -12  16  -6]
 [  1  15  20   0]] 

Einsum C =: 

[[  4  54   0   6]
 [  6 -12  16  -6]
 [  1  15  20   0]]


In [41]:
print("Transpose A =: \n")
print(A.T, "\n")

print("Einsum Transpose A =: \n")
print(np.einsum("ij -> ji", A))

Transpose A =: 

[[ 2  2  1]
 [ 6 -2  5]
 [ 5  2  4]
 [ 2  3  0]] 

Einsum Transpose A =: 

[[ 2  2  1]
 [ 6 -2  5]
 [ 5  2  4]
 [ 2  3  0]]


In [44]:
E = np.array([
   [[2, 6, 5, 2],
    [2, -2, 2, 3],
    [1, 5, 4, 0]],
   [[1, 3, 1, 22],
    [0, 2, 2, 0],
    [1, 5, 4, 1]]
])

F = np.array([
   [[2, 9, 0, 3, 0],
    [3, 6, 8, -2, 2],
    [1, 3, 5, 0, 1],
    [3, 0, 2, 0, 5]],
   
   [[1, 0, 0, 3, 0],
    [3, 0, 4, -2, 2],
    [1, 0, 2, 0, 0],
    [3, 0, 1, 1, 0]]
])

E.shape, F.shape

((2, 3, 4), (2, 4, 5))

In [46]:
print("Batch Multiplication G := \n")
print(np.matmul(E,F), "\n")

Batch Multiplication G := 

[[[33 69 77 -6 27]
  [ 9 12  0 10 13]
  [21 51 60 -7 14]]

 [[77  0 36 19  6]
  [ 8  0 12 -4  4]
  [23  0 29 -6 10]]] 



In [47]:
print("Einsum G := \n")
print(np.einsum('bij, bjk -> bik', E, F))

Einsum G := 

[[[33 69 77 -6 27]
  [ 9 12  0 10 13]
  [21 51 60 -7 14]]

 [[77  0 36 19  6]
  [ 8  0 12 -4  4]
  [23  0 29 -6 10]]]


In [54]:
A = np.array([
    [2, 6, 5, 2],
    [2, -2, 2, 3],
    [1, 5, 4, 0],
])

print('Axix 0 Sum A =: \n')
print(np.sum(A, axis=0), "\n")

print('Einsum A =: \n')
print(np.einsum("ij -> j", A))
print("------------------------------")

print('Axix 1 Sum A =: \n')
print(np.sum(A, axis=1), "\n")

print('Einsum A =: \n')
print(np.einsum("ij -> i", A))


Axix 0 Sum A =: 

[ 5  9 11  5] 

Einsum A =: 

[ 5  9 11  5]
------------------------------
Axix 1 Sum A =: 

[15  5 10] 

Einsum A =: 

[15  5 10]
